
#目标文件:依赖文件
#	规则
seqlist:main.o seqlist.o
	gcc -o seqlist main.o seqlist.o

#main.o:main.c
#	gcc -c -o main.o main.c
#seqlist.o:seqlist.c
#	gcc -c -o seqlist.o seqlist.c 
#伪目标
clean:
	rm seqlist.o main.o seqlist

